### ISSUE TITLE
"Suche" implementieren mit Spring Data Rest

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/vaadin-demo#101]
public List<LocalBuerger> queryBuerger(String query) {
        return queryBuerger(); //TODO
    }

**Comment by peter-mueller** [comment]
[Doku Links für Entities hinzufügen](http://docs.spring.io/spring-data/rest/docs/2.4.0.RELEASE/reference/html/#integration)

[JavaDoc](http://docs.spring.io/spring-data/rest/docs/current/api/org/springframework/data/rest/webmvc/support/RepositoryEntityLinks.html)

**Comment by peter-mueller** [comment]
[Stackoverflow für entitäten](http://stackoverflow.com/questions/24274127/exposing-link-on-collection-entity-in-spring-data-rest)

**Comment by FabianWilms** [comment]
Das problem, dass das "find"-field verschwindet sobald buerger-objekte existieren, liegt denke ich daran, dass wir momentan dieses Feld nur auf "resources" hinzufügen und nicht auch auf jeder einzelnen Resource die in den resources enthalten sind. Müsste man sich dann mal anschauen.

**Comment by Arne2** [comment]
Nach Fertigstellung Ticket Nr53(martkhm/barrakuda#53) in Barrakuda Bescheid geben.
