### ISSUE TITLE
Partner hinzufügen inkorrekt

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#102]
Beim hinzufügen eines partners wird der hinzugefügte partner sich selbst ebenfalls als partner hinzugefügt.

**Comment by darenegade** [comment]
In diesem Zusammenhang gleich sämtliche Partner Funktionalität reparieren. (Neu hinzugügen, Bestand hinzufügen, Löschen)

**Comment by FabianWilms** [comment]
Funktionalität ist gegeben, das problem ist, dass die gui sich nach einmaligem aufrufen nicht erneut aufbaut und ständig die alten tables verwendet.
