### ISSUE TITLE
Fehler Abfangen wenn Entity gelöscht werden soll welches als Fremdbeziehung in anderem Entity existiert.

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/vaadin-demo#105]

**Comment by peter-mueller** [comment]
Um Relationen rückwärts zu finden braucht man querys die dann auf dem /buerger/search/findBy... Endpunkt liegen: [Querys in den Repositories hinzufügen](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-creation)

z.B.:
`findByKinder(Long oid)`

@maximilian-zollbrecht _generiert das auch schon_
