### ISSUE TITLE
Events einheitlich Aufbauen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#108]
Es sollte nicht für jede Relation und die damit verbundenen Aktionen einen Eventtype geben. (SAVE_AS_PARTNER, ADD_SEARCHED_CHILD, usw)
Hier muss ein einheitliches System geschaffen werden, wodurch auch die Eventhandler der Componenten entschlackt werden.
Z.B. Soll es später nur noch die GenericTable geben und nicht für jede Relation eine abgeleitete Klasse mit überschriebenem Eventhandler.

**Comment by FabianWilms** [comment]
Fabian gibt auf. Das Problem mMn: Entweder man hat mehrere Eventtypes um die Events zuzuteilen, oder man endet später mit mehreren Konstanten die man den Events mitgibt. Irgendwie muss schließlich differenziert werden. Dies ist im Referenzsystem vor allem ein Problem da Kinder, Partner und Buerger selber alle Buerger sind. Eventuell laufe ich aber auch nur gegen die immer selbe Wand und jemand anders hat eine andere Idee.
