### ISSUE TITLE
Travis glücklich machen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#109]
TravisCI sollte wieder grün werden.
D.h. alle Tests anpassen/überarbeiten/reparieren, sodass diese wieder durchlaufen

**Comment by peter-mueller** [comment]
@xdoo @btmar :sos: Hilfe :sos:

Lokal sind die Tests bei mir grün.

**Comment by peter-mueller** [comment]
@FabianHoltkoetter  Schau dir das bitte mal an, am ende kommt ein error mit auditing mfg Peter

**Comment by FabianWilms** [comment]
Also was mir beim LOG anschauen auffällt ist zunächst, dass Travis für jedes Modul eine jacoco.exe zu finden. Hat das was zu bedeuten? 

Der nächste andere Fehler hat dann anscheinend auch wieder seinen ursprung in jacoco:
java.lang.instrument.IllegalClassFormatException: Error while instrumenting class de/muenchen/demo/service/security/SecurityRestClientImpl.
    at org.jacoco.agent.rt_1r70et.CoverageTransformer.transform(CoverageTransformer.java:94)

Und ich gebe zu, dass das gleiche dann auch beim Auditing passiert:

java.lang.instrument.IllegalClassFormatException: Error while instrumenting class de/muenchen/auditing/AuditingConfiguration.
    at org.jacoco.agent.rt_1r70et.CoverageTransformer.transform(CoverageTransformer.java:94)

Allerdings scheint das eher an diesem Jacoco zu liegen.

//Edit: Jacoco ist eine code coverage library die dazu da ist, die von Tests erfasste Menge an Code darzustellen. http://www.eclemma.org/jacoco/
Ich hab das tool nie benutzt. evtl claus fragen ob er was damit am hut hat, oder travis das selbst zu verschulden hat.

**Comment by FabianWilms** [comment]
java.io.FileNotFoundException: /home/travis/build/xdoo/vaadin-demo/API-Lib/target/jacoco.exec (No such file or directory)
[...]
java.io.FileNotFoundException: /home/travis/build/xdoo/vaadin-demo/vaadin-demo-api/target/jacoco.exec (No such file or directory)
[...]
java.io.FileNotFoundException: /home/travis/build/xdoo/vaadin-demo/Eventbus/target/jacoco.exec (No such file or directory)
[...]
java.io.FileNotFoundException: /home/travis/build/xdoo/vaadin-demo/Auditing/target/jacoco.exec (No such file or directory)

Bei den vier Teilprojekten gehts schief. Ich denke, dass man irgendeine Einstellung aktivieren muss, denn ganz zu Beginn des Logs steht folgendes:
[INFO] --- jacoco-maven-plugin:0.5.8.201207111220:report (report) @ vaadin-demo-parent ---
[INFO] Skipping JaCoCo for project with packaging type 'pom'
