### ISSUE TITLE
Generische Klassen aus den Projekten heraus trennen

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#13]
Generische Klassen sollten aus den Projekten (GUI, Service und API) heraus getrennt werden. Hierzu gehören folgende Dinge:
- HATEOAS Relations (besser eine Ableitung von Link machen und dort die Relationen pflegen)
- IdService
- ...

**Comment by darenegade** [comment]
Entspricht im wesentlichen: #3
