### ISSUE TITLE
GUI Components für Generierung ausrichten

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#137]
Z.B. die BuergerCreateForm ist mit dem derzeitigen Aufbau schlecht zu generieren und es gibt viel unnützen Code.
Beim erstellen der Templates muss dies angepasst werden.

**Comment by darenegade** [comment]
Branch gelöscht, da die Templates eh nochmal angepasst werden und dieser Stand mit dem alten Eventbus System zu Aufwendig in der Anpassung gewesen wäre.
Nach der Anpassung der Templates bitte neuen Branch auf dieses Issue erstellen und Componenten anpassen.

**Comment by darenegade** [comment]
@peter-mueller @Mirar1103 
Wenn ihr die Komponenten als Template erstellt habt, bitte dieses Ticket benutzen, um das generierte zu Übertragen.

**Comment by peter-mueller** [comment]
Komponenten werden generiert.
