### ISSUE TITLE
Local Bürger in GUI verschieben

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#138]
Meiner Meinung nach gehört der Local Bürger nicht in die API sondern in die GUI, da diese Entität nicht als Schnittstelle zum Service genutzt wird.

Dies soll hier kurz diskutiert und dann entsprechend in RefSys und Templates umgesetzt werden.

**Comment by peter-mueller** [comment]
Die Assembler in der API müssen nach Anforderung von @xdoo sowohl das DTO als auch den lokalen Buerger kennen, die müssten dann auch mit in die GUI wechseln. Dann müssen auch die RestClients überarbeitet werden.

**Comment by darenegade** [comment]
Das sollte natürlich nicht das Ziel sein.

Der Vorteil einer Verschiebung wäre die eindeutige Zuordnung der Klassen für die späteren Entwickler. Nicht dass ein Entwickler anfängt seine Views mit der DTO zu bauen, weil er den Unterschied zwischen domain und local nicht versteht. Aber wenn ein Verschieben zu aufwendig ist, können wir es auch so lassen und müssen es entsprechend dokumentieren.

**Comment by darenegade** [comment]
Closed da es hier nicht weiter geht und derzeit keine perfekte Lösung gefunden werden kann.
