### ISSUE TITLE
Volltextsuche in Spring Data Repository integrieren

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#14]
Die Volltextsuche sollte in alle Spring Data Repositories zur Verfügung stehen. Dies ist auch schon teilweise umgesetzt. Eine Anleitung hierzu gibt es unter:
http://blog.netgloo.com/2014/11/23/spring-boot-and-hibernate-search-integration/

**Comment by xdoo** [comment]
Hier muss im ersten Schritt geprüft werden, ob das nicht mit der Mandantenfähigkeit kollidiert.

**Comment by chris-koester** [comment]
Hibernate Search bietet eine Unterstützung für Mandantenfähigkeit an:
http://docs.jboss.org/hibernate/search/5.4/reference/en-US/html_single/#section-multi-tenancy

**Comment by xdoo** [comment]
Habe ich wunschgemäß in die GUI eingebaut (für den Bürger). siehe #5

**Comment by chris-koester** [comment]
Die von Hibernate bereitgestellte Schnittstelle zur Mandantenfähigkeit würde ein größeres Refactoring nach sich ziehen. Zunächst werde ich daher den Weg über einen Suchfilter gehen.
Der QueryService ist zur Zeit als Pojo implementiert. Dies würde vermutlich gemacht, um die zu durchsuchenden Felder im Konstruktor übergeben zu können. 
Eine Alternative hierzu wäre ein generisches Spring-managed Repository zu bauen (wie im verlinkten Tutorial) und bei Methodenaufruf die zu durchsuchenden Felder zu übergeben. Dies würde das Wiring vereinfachen und die Oberfläche könnte flexibel entscheiden, welche Felder durchsucht werden (bspw. über Checkboxes).

**Comment by xdoo** [comment]
@chris-koester  Initialisierung der DB durch Flyway siehe #18
