### ISSUE TITLE
GenericGrid als Komponente aufbauen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#140]
Die GenericGrid sollte:
- Eine Entität bekommen und automatisch für diese die richtigen Felder anzeigen
- Eine Suchfunktion bieten
- MultiSelect können
- DefaultButtons für die Operationen (Copy, Delete, Create, Update)
- DefaultButtons lassen sich über Methoden verstecken/anzeigen (public GenericGrid activateCopy(){..})
- Die Grid sollte eine Methode zum Hinzufügen von Buttons bieten für eigene Business Operations

Hab ich was vergessen?

**Comment by Arne2** [comment]
Nach Fertigstellung Ticket Nr54(martkhm/barrakuda#54) in Barrakuda Bescheid geben.
