### ISSUE TITLE
Grid reagiert nicht korrekt wenn ein selektierter Eintrag von extern gelöscht wird.

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/vaadin-demo#141]
Wenn man zwei Grids auf einer Seite zusammen laufen lässt, im unteren der beidne einen Eintrag markiert und den selbigen anschließend im oberen Grid löscht, verschwindet die Toolbar nicht aus der unteren grid. Bei klick auf einen der buttons taucht natürlich eine fehlermeldung auf.

![bildschirmfoto1](https://cloud.githubusercontent.com/assets/10800158/10239738/5bd33844-68d2-11e5-87f7-058c9346e7a9.png)

**Comment by darenegade** [comment]
@FabianHoltkoetter Macht es Sinn zwei gleiche Grids in einer View zu haben?

Um das Problem zu lösen müsste man wieder mit einem RefreshEvent anfangen. Da im Normalfall nur eine Grid auf der View ist, werden ständig unnötige Events geschickt. Ist jetzt nicht so geil.
Habt ihr eine andere Lösung? / Ist das nicht eher ein Spezialfall, der derzeit ignoriert werden kann?
