### ISSUE TITLE
Klasse InitApplication durch Flyway ersetzen

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#18]
Die Klasse "de.muenchen.demo.service.config.InitApplication" sollte durch Flyway (also SQL Skripts) ersetzt werden.

Siehe hierzu auch:
http://flywaydb.org/
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html

**Comment by xdoo** [comment]
@btmar brauchen wir dann die Klasse [InitApplication](https://github.com/xdoo/vaadin-demo/blob/new_project_structure/vaadin-demo-micro-service/src/main/java/de/muenchen/demo/service/config/InitApplication.java) noch? Eigentlich sollten diese DB Einträge über die SQL Skripte erfolgen, oder?

**Comment by BilelTmar** [comment]
Ja, wir könnten die Klasse InitApplication löschen.

**Comment by xdoo** [comment]
@btmar Danke. Wenn das Projekt noch baut und alle Tests durch laufen, dann bitte das Ticket schließen :)
