### ISSUE TITLE
Singletons für Navigator und EventBus

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#180]
Testen ob das von überall aus geht:

``` java
UI.getCurrent().getNavigator()
```

Und dann eine ähnliche Lösung für den EventBus bauen.

@xdoo Bitte bestätigen dass es pro GUI nur einen Navigator und einen EventBus gibt.
- [ ] :ok:

**Comment by darenegade** [comment]
In der MainUI wird der Navigator erstellt und gesetzt. Dieser sollte dann fix bleiben, da die UI für jede Vaadin Instanz auch fix bleibt.
MainUI.class:

``` java
        this.navigator = new Navigator(this, componentContainer);
        this.navigator.addProvider(viewProvider);
        setNavigator(this.navigator);
```

https://vaadin.com/book/-/page/application.lifecycle.html

**Comment by darenegade** [comment]
Beim Eventbus schaut das etwas schlechter aus, da man diesen in die UI und die damit verbundene VaadinSession packen müsste. Und zwar so, dass man es auch à la Navigator von überall bekommt. Ich sehe da derzeit keine Möglichkeit, dies auf eine schöne/praktikable Weise umzusetzen.

Dies wäre z.B. eine sehr hässliche Möglichkeit, die aus den Libs nicht möglich ist:

``` java
EventBus bus = ( (MainUI) UI.getCurrent() ).getEventBus();
```

**Comment by peter-mueller** [comment]
So OK? Mit Navigation das funktioniert so.

``` java
/**
 * Provides a simple EventBus.
 *
 * @author rene.zarwel
 */
public class EventBus extends reactor.bus.EventBus implements Serializable {

    private static EventBus eventBus = null;

    public static EventBus make() {
        if (eventBus == null)
            return eventBus = new EventBus();
        return eventBus;
    }

    private EventBus() {
        super(SynchronousDispatcher.INSTANCE);
    }
}
```

**Comment by darenegade** [comment]
Dann haben wir einen eventbus für alle Sessions aller User und das wäre vielleicht keine gute Idee. 

Von meinem iPhone gesendet

**Comment by peter-mueller** [comment]
~~Nein, ist getestet und funktioniert scheinbar.~~ Geht so nicht

**Comment by peter-mueller** [comment]
So ?:

> If you also want to access the variables of your own subclass of UI in a static way you can use the following pattern to create a getCurrent() method that is narrowed to your UI class:

``` java
public class MyApplicationUI extends UI {

   // ...

    public static MyApplicationUI getCurrent() {
        return (MyApplicationUI) UI.getCurrent();
    }
}
```

> You can then statically access your own UI subclass as follows:

``` java
MyApplicationUI.getCurrent().getMyUIScopedVariable();
```

> By that, managing ThreadLocal variables isn’t necessary any longer. Statically accessing session-scoped variables through the VaadinSession can be achieved in a similar way.

**Comment by darenegade** [comment]
Das ist besser :smile:

Von meinem iPhone gesendet

**Comment by darenegade** [comment]
Ist übrigens meine Lösung von oben

Von meinem iPhone gesendet
