### ISSUE TITLE
MainUI in GUI-Lib auslagern.

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#188]
Für #180 werden Teile des UIs in der GUI-LIB gebraucht.

**Comment by darenegade** [comment]
Den getNavigator kannst du auch in die BaseUI reinpacken, dann spart man sich das ständige getCurrent()

**Comment by peter-mueller** [comment]
Es gibt ja auch `getNavigator()` vom Objekt an sich (nicht statisch) ich weiß nicht ob das dann zu verwirrung führt. Die statische würde dann `BaseUI.getCurrentNavigator()` heißen. Ist das OK?

**Comment by darenegade** [comment]
So hab ich mir das auch gedacht, passt :smile:
