### ISSUE TITLE
[Security] der ServiceLoader findet die Adapter nicht. (im Gaia)

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#194]

**Comment by darenegade** [comment]
Das liegt an Eclipse, da dieses den META-INF Ordner nicht erstellt.
Da es keinen Vorteil bringt und noch eine "Altlast" ist, können wir den ServiceLoader rausschmeißen und einfach die benötigten Klassen direkt als Bean einbinden. Wir ja eh reingeneriert.
