### ISSUE TITLE
Security als sep. microservice aufbauen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#197]
Die Security sollte, wenn möglich, ein eigener Service sein. Dies könnte dann so aussehen:

![img_20151215_115211](https://cloud.githubusercontent.com/assets/10849776/11842929/07292b3a-a407-11e5-9052-3338b148a898.jpg)

**Comment by darenegade** [comment]
Folgende Punkte wurden geklärt:
- Rollen sind in der Domäne einheitlich
- Pro Domäne gibt es einen AuthServer mit einer DB (User + Rollen + Perm)
- Die Services propagiert seine Perms an den SecService

**Comment by huningd** [comment]
Beim Microservices Meetup Munich - November hat Sam Newman [@samnewman](https://twitter.com/samnewman?lang=de), seines Zeichens Autor des Buches Building Microservices, eine gute Präsentation zum Thema gehalten https://www.dropbox.com/s/ex7k5okl6rbta9w/securing-microservices-munich.pdf?dl=0

Auf der Spring One hat [@ fivetenwill](https://twitter.com/fivetenwill) einen Vortrag über Microservice-Security mit UAA von cloudfoundry gehalten der Code zur [Präsentation](http://de.slideshare.net/WillTran1/securing-microservices-with-spring-cloud-security) liegt auf [Github](https://github.com/william-tran/microservice-security)
