### ISSUE TITLE
I18NResolver vom Controller trennen.

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#204]
Dazu im BaseUI eine Methode `getCurrentI18n()` analog zu den anderen machen. Einen **eigenen**  _(neuen)_ I18nResolver Service schreiben der `resolve(String path)` und `resolve(Class clazz, String path)` kann.

Im BaseUI bitte einen Konstruktur einfügen der EventBus und den I18NResolver setzt.

Aus dem BuergerViewController und dem EntityController das I18n Interface ausbauen und alle Komponenten anpassen, dass die sich über BaseUI den i18n holen.

:sake: :santa: :sa:

**Comment by Arne2** [comment]
@peter-mueller  :game_die: :key: 
大好き

**Comment by peter-mueller** [comment]
![](http://www.razorbackbritt.com/wp-content/uploads/2015/09/I_have_no_idea_what_9buz.jpg)
![bildschirmfoto2](https://cloud.githubusercontent.com/assets/9094815/10731211/9465e050-7bf4-11e5-802f-8d3ef80428a6.png)
