### ISSUE TITLE
Relationen hinzufügen als eigene View (kein Modal)

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#206]
Für die Generierung von Views muss die hinzufügen Table als eigene View ausgelagert werden.

Bitte in der BuergerPartnerForm dann den AssertionError durch Navigation ersetzen :)

**Comment by FabianWilms** [comment]
Wird erledigt sobald #203 durch ist

**Comment by peter-mueller** [comment]
Danke - mein Held :)

**Comment by FabianWilms** [comment]
![fabi](https://pbs.twimg.com/media/BtEiqv3IMAAOXSf.jpg)
