### ISSUE TITLE
Fetch-Type im MicroService auf LAZY stellen

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/vaadin-demo#211]
Momentan ist der Fetch-Type bei Assoziationen überall auf EAGER gestellt. Dies führt zu Fehlverhalten der Suche. Bitte umstellen in allen Domain-Objekten.

**Comment by maximilian-zollbrecht** [comment]
Könnte andere Probleme bringen: martkhm/barrakuda#125
Relations konnten bei gleichen Entities nicht gesetzt werden.
[So](http://stackoverflow.com/questions/4362104/strange-jackson-exception-being-thrown-when-serializing-hibernate-object) eine Exception kam da in etwa.

**Comment by FabianWilms** [comment]
Konnte den Fehler nachvollziehen @maximilian-zollbrecht . Nachdem ich den Fetch.-Type wiede rauf EAGER umgestellt hatte, konnte ich wieder Partner und Kinder hinzufügen, allerdings bestand weiterhin das Problem, dass die Suche nicht ging.
Zum testen habe ich abschließend garkeinen FetchType gesetzt (der Default bleibt EAGER) und (warum auch immer) funktioniert nun sowohl die Suche, als auch das hinzufügen von Assoziationen.

Da maxi jetzt erst Montag wieder kommt, sollte @peter-mueller sich meine Lösung mal anschauen und nach evtlen Fehlern suchen.

**Comment by peter-mueller** [comment]
:thumbsup:

Fabian Holtkötter notifications@github.com schrieb am Mo., 2. Nov. 2015,
14:23:
