### ISSUE TITLE
GenericGrid ohne Controller & Controller->DataStore

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#212]
Abhängigkeit zum Controller vom GenericGrid lösen.

**Comment by peter-mueller** [comment]
:flags: Ich geb auf, die DataStores müssten dann auch generisch sein.

**Comment by FabianWilms** [comment]
@peter-mueller Was genau war nochmal der Auslöser für diesen Änderungswunsch? Würde es nicht reichen der BuergerGrid als Übergabewert einfach einen BeanItemContainer zu übergeben?

**Comment by peter-mueller** [comment]
Das Generic Grid ist sehr stark an die Implementierung des DataStores gebunden (Die Sammlung aller Bürger **muss** ein BeanItemContainer sein). Außerdem wird für das Lesen der Bürger der EventBus ignoriert.

Es geht aber und das recht stabil & auch im generierten deswegen ist das im Sprint KW 45/46 nicht so wichtig.

**Comment by darenegade** [comment]
@peter-mueller Was hältst Du von dieser Idee? (Siehe letzten Commit zu diesem Ticket)

Die Grid kann entweder mit festem Container initialisiert werden, oder sie holt sich über die Entitäts Klasse und den Eventbus selber die Daten.

**Comment by FabianWilms** [comment]
find ich gut
