### ISSUE TITLE
Copy Operation funktioniert nicht bei Referenzen

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#23]
Hat man ein objekt mit Referenzen, dann funktioniert die copy operation nicht richtig. Es wird folgende Fehlermeldung ausgegeben:

<code>org.hibernate.HibernateException: Found shared references to a collection:</code>

**Comment by xdoo** [comment]
Tests bitte in #21 nachziehen.

**Comment by martku** [comment]
Das Kopieren sollte schon direkt in den Entities implementiert sein, da dieses das Wissen darüber besitzen, was kopiert werden soll und was nicht. Entsprechend wäre ich für die Einführung von copy constructors. Wie siehst du das Claus?

**Comment by xdoo** [comment]
Sehe ich nicht so. Der Service ist aus meiner Sicht der richtige Ort, weil er später die Möglichkeit bieten wird, Operationen zu überschreiben. Ich denke der einzige, der weiß, was wiklich kopiert werden soll ist der Entwickler ;) Ich würde das deshalb im Service belassen und im ersten Schritt einfach alles kopieren. Bei der Implementierung kann der Entwickler das dann einschränken. Z.b. ist das Kopieren eines Geburtsdatums beim Bürger in den meisten Fällen nicht sehr sinnvoll.

**Comment by xdoo** [comment]
Chris hat mich gerade angefunkt und gemeint wir hätten beide recht - womit er sicherlich recht hat :) Wir können aus dem Service heraus den Konstruktor aufrufen. Wichtig ist nur, dass wir die Möglichkeit erhalten, die Operation im Service über schreiben zu können.

**Comment by martku** [comment]
Ja, so war es angedacht. Verwendet wird es im Service. Erspart und dann aber Arbeit, wenn die Entity verändert wird, da nur diese dann angepasst werden muss.

**Comment by chris-koester** [comment]
Super, sind wir ja eigentlich alle zum gleichen Schluss gekommen. Dann sollte es ja richtig sein. ;)

**Comment by xdoo** [comment]
Da mir das Ticket zugewiesen ist, kann ich es machen. Heute geht allerdings nicht. Wenn es dringend ist, Martin dann bitte schnell selbst machen. Es muss ja nur der Code aus dem Service in den Konstruktor geschoben werden.

**Comment by martku** [comment]
@btmar: Wie gestern schon angesprochen, bitte alle Entities um diesen Kopier-Konstruktor erweitern und dann im Service nur noch aufrufen, danke.

**Comment by xdoo** [comment]
Wenn die Tests grün sind, bitte Ticket schließen.
