### ISSUE TITLE
Grid-Spalten verwenden kein Icon mehr

### ISSUE THREAD

**Issue by FabianWilms** [xdoo/vaadin-demo#235]
In der neuen GenericGrid ist es nicht mehr möglich für die Spalten FontAwesome-icons in den ApplicationProperties anzugeben.

`«entität».«feld».column_header.icon =`

**Comment by darenegade** [comment]
Da ich eh gerade bei der Grid war, hab ich mir das mal angeschaut.
Bei der Grid kann man nur ein String als HeaderCaption übergeben und kein HTML.

Daher schließe ich das Ticket.

Kann wieder geöffnet werden, wenn die Grid CaptionMode unterstützt.
