### ISSUE TITLE
DateValidation auf MicroService Seite funktioniert nicht

### ISSUE THREAD

**Issue by Arne2** [xdoo/vaadin-demo#240]
Die Validation des Datums auf MicroService Seite funktioniert nicht. Dies bitte beheben.

**Comment by Arne2** [comment]
![datevalidationerror](https://cloud.githubusercontent.com/assets/13729982/10931804/4b303326-82cb-11e5-905a-1c9880c891e5.png)

![datevalidationerror1](https://cloud.githubusercontent.com/assets/13729982/10931808/50fa84fa-82cb-11e5-9918-6d86f99f4b6e.png)

**Comment by FabianWilms** [comment]
~~verstehe ich nicht? was sollen mir die screenshots zeigen?~~
hat sich

**Comment by Arne2** [comment]
Ich hätte es mit paint rot markieren können :D

**Comment by maximilian-zollbrecht** [comment]
Bei mir hat es eben funktioniert.
List of constraint violations:[
    ConstraintViolationImpl{interpolatedMessage='muss in der Vergangenheit liegen', propertyPath=geburtsdatum, rootBeanClass=class de.muenchen.demo.service.gen.domain.Buerger, messageTemplate='{javax.validation.constraints.Past.message}'}
]

**Comment by Arne2** [comment]
Wie schon angemerkt habe, verhielt sich dieses Problem auch bei mir nicht als reproduzierbar. Daher wird dieses Ticket geschlossen. Sollte das Problem wieder auftreten einfach das Ticket neueröffnen!
