### ISSUE TITLE
Beispiel für Relationen zu anderen Entitäten mit Bedingung NotNull

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#260]
Hier können z.B. die Wohnung für eine erforderliche ManyToOne bzw. OneToOne Relation und Staatsangehörigkeit für eine ManyToMany hergenommen werden.

**Comment by darenegade** [comment]
Lösung in Zusammenhang mit: https://github.com/xdoo/gaia/issues/41

**Comment by FabianWilms** [comment]
https://github.com/martkhm/barrakuda/issues/267
ist erledigt.
