### ISSUE TITLE
Buttons in Grid

### ISSUE THREAD

**Issue by maximilian-zollbrecht** [xdoo/vaadin-demo#265]
Die Buttons in Grids sollten immer sichtbar sein, aber deaktiviert, wenn eine Funktion nicht verfügbar ist.

**Comment by darenegade** [comment]
Buttons immer zu aktivieren, ist meiner Meinung nach nicht richtig. Der Nutzer kann sie sich ja nach seinen Belieben einstellen.

Was meinst du mit: "deaktiviert, wenn eine Funktion nicht verfügbar"?

**Comment by FabianWilms** [comment]
Die Idee war, anstatt die buttons fur single und multiselect verschwinden zu lassen, sie einfach auf disabled zu stellen. Also so, dass sie "ausgegraut" sind. So weiß der Nutzer direkt welche Funktionen verfügbar sein können, und die Knöpfe Popen nicht einfach auf.

**Comment by darenegade** [comment]
An sich eine gute Idee, aber das sollte nur Buttons betreffen, die auch verfügbar sind. Ich würde daher die Buttons nur ausgrauen wenn sie aktiviert sind aber derzeit, aufgrund der Auswahl oder so, nicht zur Verfügung stehen. 

Von meinem iPhone gesendet

**Comment by FabianWilms** [comment]
Neeein das ist sowieso klar. Nur konfigurierte buttons.

darenegade notifications@github.com schrieb am Mo., 30. Nov. 2015 17:44:

**Comment by darenegade** [comment]
Na dann sind wir uns ja einig. Die Änderung ist schnell erledigt. Man muss nur eine Methode in der Grid anpassen. 

Von meinem iPhone gesendet

**Comment by FabianWilms** [comment]
Na dann hab ich ja was zu tun den Rest der Woche 👍

**Comment by Arne2** [comment]
Das ist doch nur anstelle von setVisible, setEnabled aufrufen

**Comment by FabianWilms** [comment]
It was only a joke.

**Comment by Arne2** [comment]
I dont understand jokes.

Nicht von meinem iPhone gesendet
