### ISSUE TITLE
Ports ändern

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#278]
Die Ports vom RefSys sollten geändert werden, damit Gaia parallel laufen kann.
(Wichtig z.B. für das IssueSystem)

**Comment by Arne2** [comment]
Gibt es im Wiki irgendwo eine Liste von Ports, die schon in Verwendung sind?

**Comment by darenegade** [comment]
Nein, aber du kannst gerne mal eine erstellen

**Comment by Arne2** [comment]
Krieg ich grad nicht fertig. Wenn nötig bitte bearbeiten, sonst mach ich nach der PBLV weiter. :sorry:

**Comment by xdoo** [comment]
Was ist RefSys? Grundsätzlich kann man immer mit Port 0 arbeiten. Spring Boot nimmt dann einen zufälligen Port. Der wird in die Logausgaben geschrieben.

**Comment by FabianWilms** [comment]
ReferenzSystem (also vaadin-demo)

**Comment by darenegade** [comment]
Siehst du, der Fabian hat es verstanden :wink: 

Dieses Ticket ist schon recht alt und sollte durch das nun verwendete client-seitige Service Discovery obsolet gewordern sein.
