### ISSUE TITLE
Reset Search - GGrid

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#289]
Der Reset von der Suche muss noch auf den neuen Containertyp umgestellt werden.

**Comment by FabianWilms** [comment]
Den Fehler habe ich in meinem PR #287 schon gefixt

**Comment by FabianWilms** [comment]
https://github.com/xdoo/vaadin-demo/pull/287/files#diff-ed4bbf0a111cea32e5b6795ef751f0b9R263

**Comment by darenegade** [comment]
Okay, konnte ich nicht wissen, da es ja nicht zu dem Ticket https://github.com/xdoo/vaadin-demo/pull/287 dazugehörte. :wink:

**Comment by FabianWilms** [comment]
🙊
