### ISSUE TITLE
Aktionsmeldungen an i18n Service anbinden

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#29]
Die Aktionsmeldungen im Controller sind aktuell hard gecoded. Diese müssen über den i18n Service gespeist werden, damit sie konfigurierbar sind.

**Comment by xdoo** [comment]
Gehört zu #38 

Bitte entsprechend abstimmen.

**Comment by maximilian-zollbrecht** [comment]
Closed with merge.
