### ISSUE TITLE
Anwendungsstruktur nach generativem Ansatz ausrichten

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#3]
Die Anwendungsstruktur muss auf den generativen Ansatz ausgerichtet werden. Konkret müssen voll generierte Teile von editierbaren Teilen getrennt werden. Zusätzlich müssen Querschnitts-Funktionalitäten identifiziert und in entsprechende Bibliotheken ausgelagert werden. Spontan fallen mir hierfolgende Dinge ein:
- Bibliothek zur Verwaltung von Nutzern und Rollen.
- Bibliothek für die Innenrevision (siehe hier auch http://docs.jboss.org/envers/docs/)
- ...

Bitte für jede identifizierte Bibliothek ein eigenes Issue öffnen.

**Comment by martku** [comment]
Folgende Funktionlität soll ausgelagert werden:
- Verwaltung der Nutzer und Rollen (#49)
- Auditing durch Innenrevision (#51)
- Fehler-Handling (#83)
- Service-Info (#84)
- I18N (#85)
- Hateoas (#86)
- Eventsystem (#88)
- Generische UI Komponenten, wie CancelButton (#89)

Es soll dann so sein, dass die eigentlichen Projekte (API, MicroService, GUI) diese als dependency eingetragen haben. Dieses Ticket würde ich als Sammelticket noch offen lassen, für den Fall, dass weitere Bibliotheken sinnvoll erscheinen sollen.

**Comment by darenegade** [comment]
Die Struktur ist entsprechend aufgebaut und vorhandene Elemente sind aufgeteilt. Bei Erweiterungen wird dieser Ansatz immer mit berücksichtig.
