### ISSUE TITLE
Zuständigkeiten der drei Projekte (GUI / Service / API) klar trennen

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#30]
Die Zuständigkeiten der drei Projekte (GUI / Service / API) müssen klar getrennt werden. Beispielsweise darf es nur ein DTO geben (z.B. BuergerResource). Aktuell gibt es aber noch eines im API und eines im Service Projekt.

**Comment by xdoo** [comment]
Issue wurde versehentlich gelöscht.

**Comment by darenegade** [comment]
Zuständigkeit ist aus meiner Sicht momentan gut getrennt.
#37 Wurde entsprechend auch geschlossen.
Ansonsten kommen jetzt die neuen Bibliotheken, die die Zuständigkeit weiter trennen. #3
