### ISSUE TITLE
Gui für Rollen und Rechte

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#303]
Gaia soll eine Ansicht bieten in der man Rollen und Rechte verwalten kann.

Trotz der anstehenden Security-Änderung wird die API sich kaum/nicht ändern, weshalb die GUI bereits jetzt implementiert werden kann.

Die erstellten Views/Components sollen dann in eine Library (evtl. GUI-Lib) gepackt werden, um in allen generierten Projekten zur Verfügung zu stehen.

https://github.com/xdoo/gaia/issues/135

**Comment by FabianWilms** [comment]
@maximilian-zollbrecht https://demo.vaadin.com/valo-theme/#!selects

**Comment by maximilian-zollbrecht** [comment]
closed in #308
