### ISSUE TITLE
Validation für Keywords

### ISSUE THREAD

**Issue by Arne2** [xdoo/vaadin-demo#307]
Es soll angeboten werden Eingaben auf Keywords wie z.B. Java oder Barrakuda zu überprüfen.

**Comment by Arne2** [comment]
@martkhm Habe folgende KeyWords für Barrakuda:
"customTextType","customDateType","customNumberType","customLogicType","customListType","given","purpose","then","package","entity","version","any","inThePast","inTheFuture","optional","mainFeature","searchable","businessAction","auditChanges","external","oneToMany","oneToOne","manyToMany","manyToOne",
"button","navigatesTo","for","component","view","Table","mainview","appearsInMenu","relComponent","CreateForm","ReadWriteForm","type","ReadEditComponent","AddTable","ReadForm","UpdateForm","ReadComponent"

**Comment by martku** [comment]
Eine aktuelle Liste der KeyWords der Sprache ist immer in folgender Datei enthalten (alles was zwischen den ' und gleichzeitg vor dem = steht):

src-gen/de/muenchen/dsl/barrakuda/parser/antlr/internal/InternalBarrakuda.tokens

**Comment by martku** [comment]
Wenn sowieso eine API gebaut wird, dann wäre dafür eine Methode sinnvoll.
barrakuda/# 200

Kann es sein, dass dieses Ticket eigentlich in Barrakuda bzw. Gaia sein sollte?

**Comment by FabianWilms** [comment]
Es soll in eine der libs mit reingebracht werden, damit man in Barrakuda bei einem CustomTextType sagen kann, man möchte einen KeywordFilter haben. Im Generat wird dann einfach der Filter von Arne aus der lib benutzt.

Was für eine Methode denn? Zum abfragen der Keywords?

**Comment by Arne2** [comment]
Ich hab eine Annotation geschrieben, die zur Validation dient.

**Comment by martku** [comment]
@FabianHoltkoetter Der KeywordFilter wird dementsprechend zur Laufzeit der fertigen Anwendung verwendet. Dachte er wird hauptsächlich für Gaia verwendet -> dann macht dieses Ticket hier Sinn :-)
