### ISSUE TITLE
Kind zu Bürger über Suche hinzu fügen 

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#32]
Es muss noch der Fall implementiert werden, indem ein vorhandener Bürger einem anderen vorhandenen Bürger hinzugefügt werden kann. Hierzu müssen folgende Schritte getan werden:
- Es muss der Button "hinzufügen" als GUI Komponente erstellt werden
- In der GUI Komponenten "BuergerChildTab" muss der Button "hinzufügen" eingebaut werden
- In der Tabelle "BuergerSearchTable" muss für jeden Datensatz eine "auswählen" Schaltfläche zur Verfügung stehen. Diese ist im Default nicht sichtbar, kann jedoch - wie die anderen auch - bei Bedarf zugeschaltet werden.
- Im BuergerViewController muss eine Factory Methode zum initialisieren der Suchtabelle erstellt werden. Diese Methode schaltet die Default Schaltflächen aus und die "auswählen" Schaltfläche an.
- Es muss eine View erstellt werden, die die Suchtabelle und eine "Abbrechen" Schaltfläche enthält.
- Es muss die entsprechende Logik im BuergerViewController, BuergerService und BuergerRestClient erstellt werden (inkl. Events).

Die Auswahl wird aus der Komponente "BuergerChildTab" aus angesprungen. Bei "Abbrechen" auf der Auswahlseite soll der Nutzer wieder zurück zur View gelangen, die die aktive "BuergerChildTab" beinhaltet. Wenn ein Bürger ausgewählt wird, dann ist das Default Verhalten, dass ebenfalls auf die "ChildTab" View zurück navigiert wird.

**Comment by Mirar1103** [comment]
Funktionalität erstellt und in den Master branch eingepflegt
