### ISSUE TITLE
Diakritische Zeichen

### ISSUE THREAD

**Issue by martku** [xdoo/vaadin-demo#33]
Die Eingabe (über die GUI) und Verarbeitung von diakritischen Zeichen soll möglich sein. Bitte überprüfen und wenn nötig entsprechend Anpassen.

**Comment by Arne2** [comment]
Validator wurde beim commit hinzugefügt, dass nur Zeichen zugelassen werden, die einer bestimmten Menge sind (Diakritsche Zeichen eingeschlossen)
