### ISSUE TITLE
Bürger zu Staatsangehörigkeit hinzufügen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#36]
Ein Bürger kann eine oder meherere Staatsangehörigkeiten haben. Die Auswahl der Staatsangehörigektien erfolgt dabei über eine Drop-Down Menü
mit allen möglichen Staatsangehörigkeiten. Die Staatsangehörigkeiten werden dabei vom Config-Server geladen.

**Comment by maximilian-zollbrecht** [comment]
Staatsangehörigkeiten werden von einem externen Service geholt und sind eigene Entities.
Das Hinzufügen einer Relation zwischen bestehenden Entitäten muss noch komplett eingebaut werden.

Die Auswahl könnte zwar über eine Combobox erfolgen, allerdings ist ebenfalls möglich die Anzeige analog zu anderen Entitäten zu machen.(TableView mit bereits hinzugefügten Elementen + Button zum hinzufügen + Auswahl über neue Tableview mit suche)

Da die Staatsangehörigkeit ein sehr spezieller Fall ist macht es denke ich Sinn zuerst einen anderen Fall einzubauen. (z.B. Pass oder Sachbearbeiter)

**Comment by maximilian-zollbrecht** [comment]
Hat sich erledigt, denke ich.
