### ISSUE TITLE
DTOs einheitlich in die API verschieben - Entschlackung

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#37]
Momentan werden im microservice nicht die DTOs aus der API für die Übertragung genutzt. Hier sollen auf beiden Seiten Client - Server die gleichen 
DTOs gentutz werden.

**Comment by xdoo** [comment]
@Mirar1103  Bitte hier drauf achten, dass die Beans, die in der Oberfläche verwendet werden, ungleich den Entities des Services sind. Das muss auch weiterhin so bleiben. Es ist zu überlegen, wie wir mit den Assemblern umgehen. Diese sind aktuell für die GUI im API Projekt. Das würde aus meiner Sicht passen, weil ein Nutzer der API hat ja immer die Möglichkeit direkt gegen die DTOs zu gehen und seine eigenen Assembler zu schreiben. Oder er nutzt alles was schon da ist.

**Comment by xdoo** [comment]
Gehört zu #30
