### ISSUE TITLE
I18N Propertys im Service umsetzen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#38]
Die I18N Propertys sind momentan hard gecoded im Service. Hier sollen die Propertys aus den Resources geladen werden. Dazu soll auch zur 
vereinheitlichung die Struktur der Propertys ins JSON Format gewandelt werden

**Comment by xdoo** [comment]
Hier noch ein paar Hintegrundinformationen:

Jeder Text und auch jedes Icon (FontAwesome Icon) muss konfigurierbar sein. 

Es muss eine Namenskonvention geben, um ein Property wirklich eindeutig, aber trotzdem leicht findbar zu machen. Aktuell wird die Konvention <pre><MODUL>.<ENTITY>.<GUIKOMPONENTENTYP>.<TEXTTYP></pre> verwendet - wobei sich das auch nicht konsequent durch zieht. Hierbei kommend as MODUL + ENTITY aus dem Controller, der GUIKOMPONENTENTYP wird aus dem Interface <code>de.muenchen.vaadin.ui.util.I18nPaths</code> geholt, der TEXTTYP ergibt sich aus der aufgerufenen Methode in des Interfaces <code>de.muenchen.vaadin.services.MessageService</code>.

Bitte zur eigentlichen Implementierung auch ein entsprechendes Konzept (das kann an das vorhandene angelegt sein - muss aber nicht) entwickeln und beschreiben (am besten im Wiki).
