### ISSUE TITLE
Beziehungen zwischen Bürgern

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#50]
Als Nutzer möchte ich Beziehungen zwischen Bürgern anlegen können (z.B. Ehepartner, Lebensgemeinschaft usw.)

**Comment by xdoo** [comment]
Folgende Sachen sind mir noch aufgefallen:
- Bei Auswahl eines Partners wird die "Kinder" Meldung angezeigt.
- Bitte kein Modal Fenster verwenden.
- Es kann mehr als ein Partner hinzugefügt werden (was in Deutschland tendenziell nicht erlaubt ist).

**Comment by darenegade** [comment]
Zu 1: 
Dies ist bekannt, aber hier musste das I18N Path Konzept angepasst werden.
Es wurde der Text über den Path "i18n.de-DE.buerger.notification.success.add.label" geholt. Dort gab es keine gute Möglichkeit zusätzliche Attribute anzufügen.
Ich habe im I18N jetzt die Möglichkeit hinzugefügt, dass man zus. Attribute eingeben kann.

Zu 2:
Was spricht gegen das Modal Fenster? Damit wird die Interaktion im Hintergrund unterbunden. Also kein ViewChange oder neues SelectWindow solange das Fenster noch offen ist.

**Comment by FabianWilms** [comment]
Es kann jetzt nur noch ein PArtner hinzugefügt werden. Ich baue nun noch Warnmeldungen auf GUI-seite ein, damit dies klar ist.
