### ISSUE TITLE
BürgerView kann (unendlich oft) erstellt werden.

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#53]
Beim klicken auf den Button `BürgerPfege` im Nav-Bereich wird jedesmal eine Bürgerview unten angehängt.

![screenshot_verkleinert](https://cloud.githubusercontent.com/assets/9094815/9376180/e027b506-4709-11e5-9479-74be128cacf1.png)

**Comment by peter-mueller** [comment]
Jetzt werden nurnoch die Überschriften hinzugefügt.
![bildschirmfoto2](https://cloud.githubusercontent.com/assets/9094815/9378872/36951404-4725-11e5-9fb0-1f037697df8c.png)

**Comment by darenegade** [comment]
Überprüfung eingefügt, ob auf die gleiche View navigiert wird
