### ISSUE TITLE
Navigation in der GUI überarbeiten

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#68]
Die Navigation funktioniert nicht korrekt.
Das Problem kann man durch folgende Schritt nachvollziehen:
1. BürgerTableView öffnen
2. Einen Bürger mit Kindern in der Tabelle auswählen und zur BürgerReadView wechseln
3. Ein Kind zur Ansicht auswählen und zur BürgerReadView des Kindes wechseln
4. Auf zurück klicken
-> Hier gelangt man nun wieder auf die BürgerTableView und nicht zum Elternteil des Kindes zurück

Bei der BürgerCreateView hatte er mich auch schon mal falsch wieder zurück geleitet, doch dies konnte ich nicht mehr replizieren.

Momentan wird die navigation z.B. in der BürgerCreateForm über die Strings "navigateTo" und "back" gesteuert, welche im Konstruktor gesetzt werden. Kann man das nicht besser machen?

Hier sollte mehr mit dem push, pop und peek vom Controller gearbeitet werden. Und die Navigation an allen Stellen überprüft werden.

**Comment by peter-mueller** [comment]
#67 , hat aber nichts mit push/pop zu tun. betrifft nur die Navigation generell;

**Comment by peter-mueller** [comment]
Momentan wird das navigateTo ja immer manuell vergeben, ist das aber nicht implizit durch den EventTyp schon vorgegeben?
- z.B. `CREATE` -> `BuergerCreateView`

From müsste doch auch im Controller bestimmt werden könne?

**Comment by xdoo** [comment]
Nein. Hinter dem Navigate to steht ja immer eine view (NAME). Die views sind etwas, was wir nur initial raus generieren werden und was der Entwickler dann so anpassen kann, wie er will. D.h. er kann neue views definieren um z.B. Workflows zu definieren. 

Beispiel 1:
Wir legen einen Bürger an. Wenn der Nutzer speichern drückt, dann soll er aber nicht auf die Tabelle zurück kommen, sondern auch noch eine Wohnung anlegen. 

Beispiel 2:
Das create Formular befindet sich auf der Übersichtsseite. Dann steht gar nichts in navigateTo drin. 

Das Event ist an die Aktion gebunden, das Feld navigateTo definiert den Page Flow.

**Comment by xdoo** [comment]
Mir ist nicht klar, wie "from" im Controller definiert werden kann. Der weiß ja nichts von den views. Wie gesagt: der Entwickler kann beliebige Views definieren und dort GUI Componenten (auch eigene) platzieren. Ich würde sagen der Controller weiß nicht woher ein Event kommt. Wenn es ein punkt gibt, wo man das raus kriegen kann, dann müsste es der Navigator sein.

**Comment by xdoo** [comment]
Mir ist klar, dass das eine einigermaßen komplexe Sache ist. Wenn wir das konzeptuell rund hin bekommen, dann ist das aber auch der Schlüssel zum Erfolg, weil der Entwickler sich wirklich darauf konzentrieren kann die GUI schön zu machen und die fachliche Logik einzubauen. Alles andere passiert magisch :)

Bitte das Konzept hinter der Navigation auch im Wiki dokumentieren.

**Comment by peter-mueller** [comment]
Ich werde jetzt erst einmal die Navigation von den AppEvents trennen und komplett statisch machen.

**Comment by peter-mueller** [comment]
Beim Klick auf den Kind oder Partner Button wird die Seite ganz nach oben gescrollt.
@darenegade bitte mal checken ob das so gewollt ist

**Comment by FabianWilms** [comment]
@Mirar1103 Partner hinzufügen funktioniert nicht mehr

**Comment by darenegade** [comment]
@FabianHoltkoetter Partner hinzufügen geht wieder. Hier gab es wohl ein Merge Problem.

@peter-mueller Gute Frage. Dies ist so nicht gewollt. Schaut nach einem Vaadin Bug aus.

**Comment by FabianWilms** [comment]
@peter-mueller https://dev.vaadin.com/ticket/18271
