### ISSUE TITLE
Wohnung zu Bürger hinzufügen

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#7]
Als Sachbearbeiter will ich einem Bürger eine oder mehrere Wohnung(en) hinzu fügen können. 

Abnahmekriterium:
Angenommen ich füge für dem Bürger Hans Meier zwei Wohnungen zu, so müssen diese beim Aufruf des Bürgers in der Liste der Wohnungen zu finden sein.

**Comment by xdoo** [comment]
Aus meiner Sicht ist das implementiert und auch getestet (mit der Einschränkung von #21). Wenn du das auch so siehst, dann würde ich dieses issue schließen. 

Vorsicht: hier gibt es noch einen Branch "wohnung". Der muss ggf. gemerged werden. Auf jeden Fall ist er dem master Branch voraus.

**Comment by BilelTmar** [comment]
Der Branch "wohnung" wurde bereits vor 16 Tagen in den new_project_structure Branch gemerged. Seit dem kamen keine neuen Commits mehr hinzu, wodurch wir (Martin und ich) diese gelöscht haben.
