### ISSUE TITLE
Fehlermeldung und default bei falscher Localization

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#71]
Sollte im Browser eine Localization eingestellt sein, die wir nicht haben, sollte ein default mit einer entsprechenden Meldung gezogen werden. Ansonsten schaut das so aus und man kann gar nichts machen:

![local_error](https://cloud.githubusercontent.com/assets/712911/9513329/49daa7bc-4c8f-11e5-9840-1a10cea4d482.png)

**Comment by peter-mueller** [comment]
Das liegt an einem FontAwesome Icon dass noch aus den Properties geladen wird.
Momentan wird immer der Path zurückgegeben der nicht gefunden werden konnte (für DEBUG). Wie zum Beispiel bei i18n.en_US.{{...}}}.page.title.

Ein Pfad kann nicht als FontAwesome erstellt werden -> Fehler. Bei normalen Strings tritt dies nicht auf.

~~**Frage**: Sollen Icons überhaupt konfiguriert werden? Es gibt nurnoch einen Fall wo das Icon **über i18n** geladen wird.~~

Icons müssen für Entitäten in z.B. der Tabelle konfigurierbar sein.

**Frage:** Werden auf Tabellen wirklich Icons benötigt?  Wie sollen die generiert werden?

**Comment by xdoo** [comment]
Ich denke wir sollten das anbieten, weil Icons einfach ein schönes Mittel sind, um eine grafische Oberfläche individuell zu gestalten und den Nutzer visuell zu unterstützen. Prinzipiell ist es ja einfach zu realisieren. Die FontAwesome Icons haben immer einen Identifier. Den können wir als Property angeben. Ist kein Identifier angegeben, wird kein Icon dargestellt. Aus dem IDentifier rendern wird das Icon. 

<code>c.setIcon([I18N_FONTAWESOME_ID])</code>

**Comment by peter-mueller** [comment]
Der Fehler sollte jetzt behoben sein.

Falls eine Sprache nicht verfügbar ist, ist dann das verhalten mit den Pfaden so ok, oder soll dann versucht werden de_DE zu laden?

**Comment by darenegade** [comment]
Du hast die Sprache auf Englisch fest eingestellt. Dadurch konnte beim mir nix mehr angezeigt werden. Es sollte schon der Standardwert vom Browser genutzt werden, jedoch muss vorher auf Unterstüzung überprüft werden. Und falls es nicht unterstüzt wird, dann sollte ein Default Wert, z.B. deutsch, genommen werden.
Ich habe das mal als Beispiel implementiert. Die Überprüfung ist noch nicht fix und sollte noch überarbeitet werden.

**Comment by peter-mueller** [comment]
Die Lokale muss ja dann konfigurierbar sein z.B. in der GUI über Einstellungen oder über den Accept-Language Header des Browsers.

Hier muss _meiner Meinung_ nach dann wirklich geprüft werden was verfügbar ist.

Das bedeutet das der Setter für die Locale bei einer nicht unterstützen Lokale einen Fehler wirft.
