### ISSUE TITLE
Authentifizierung über LDAP UND DB

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#72]
Bitte prüfen, ob es möglich ist, sowohl LDAP, als auch DB als Authetication Provider zu benutzen. Ganz konkreter Fall "IT ind Wahllokal":

Hier soll eine Anwendung entstehen, mit der externe und interne MA gleichzeitig arbiten. Extern meint hier Menschen, die für einen Tag als Wahlvorstand arbeiten und natürlich keinen LDAP Eintrag haben. Im besten Fall können sich die internen MA über LDAP authetifizieren und die Externen über DB. 

Shiro hat hier so ein Konzept, der unterschiedlichen Authetication Provider.

http://shiro.apache.org/architecture.html

**Comment by darenegade** [comment]
Das ist bei Spring echt easy. Man kann einfach die verschiedenen ConfigAdapter als Bean hinzufügen und sie laufen dann parallel.

Ich habe jetzt die Order von LDAP höher als die von der DB gesetzt, sodass man in der DB das Passwort NULL setzen kann und nur noch der LDAP funktioniert.

Später beim generieren kann der Nutzer die Authentifizierungsarten auswählen und diese werden dann als Bean einfach reingeneriert.
