### ISSUE TITLE
Kind von Bürger entfernen

### ISSUE THREAD

**Issue by Arne2** [xdoo/vaadin-demo#73]
Möglichkeit sollte bestehen bei der Kinder Tabelle eines Bürgers neben dem hinzufügen auch Kinder löschen zu können.

**Comment by Arne2** [comment]
tabelle wird noch nicht aktualisiert

**Comment by darenegade** [comment]
Sorry Arne, aber ich hatte den Fehler zufällig gerade gefunden. ;)
