### ISSUE TITLE
GUI Projekt kann nicht gebaut weden

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#75]
Beim Bau erscheint folgender Fehler:

<pre>
--- maven-compiler-plugin:2.3.2:compile (default-compile) @ vaadin-demo-gui ---
Compiling 54 source files to /home/claus/NetBeansProjects/vaadin-demo/vadin-demo-gui/target/classes
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
de/muenchen/vaadin/ui/components/BuergerCreateForm.java:[167,125] error: cannot find symbol
 class BuergerCreateForm
de/muenchen/vaadin/ui/components/BuergerCreateForm.java:[167,150] error: cannot find symbol
 class BuergerCreateForm
de/muenchen/vaadin/ui/components/BuergerCreateForm.java:[168,71] error: cannot find symbol
 class BuergerCreateForm
de/muenchen/vaadin/ui/components/BuergerCreateForm.java:[168,96] error: cannot find symbol
4 errors 
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 4.248s
Finished at: Thu Aug 27 12:15:09 CEST 2015
Final Memory: 26M/168M
</pre>

**Comment by darenegade** [comment]
Die Action wurde als SimpleAction erweitert aber nicht in der CreateForm angepasst. Das hab ich gefixt und bei mir läuft es nun ohne Probleme.
