### ISSUE TITLE
Security aus microservice rauslösen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#78]
Security mit Entitäten rauslösen und in MS einbinden

**Comment by peter-mueller** [comment]
Man könnte einen OAuth Server mit JWT tokens bauen, die die `ROLES`/`PERM` enthalten.

>Dazu muss man die Bestätigung des Nutzers abstellen: 
>```java
public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
      clients.inMemory()
          .withClient("acme")
          .secret("acmesecret")
          .autoApprove(true) // Keine Meldung zur Bestätigung des Zugriffs anzeigen
          .authorizedGrantTypes("password")
          .scopes("scope");
}
```

>Also **ohne** das:
>![](https://developer.github.com/images/oauth_prompt.png)

Evtl. hab ich das aber auch falsch verstanden bzw. ist das OverKill.

**Comment by peter-mueller** [comment]
#93

**Comment by darenegade** [comment]
Ansatz: Die Security kennt keine Mandantenfähigkeit. Somit kann Sie ohne Circulare Referenzen rausgelöst werden. Im Idealfall nutzt das Security Package die fertigen Spring Klassen. (User / Authority/ usw) Wenn die App jetzt die Mandanten benötigt, muss die User Klasse in der App überschrieben werden.
