### ISSUE TITLE
Bürger in Kindtabelle nach bearbeiten des Bürgers

### ISSUE THREAD

**Issue by Arne2** [xdoo/vaadin-demo#80]
Nach bearbeiten eines Bürgers wird der Bürger bei sich selbst als Kind angezeigt, obwohl er keiner ist...
(nur bis aktuallisation der Tabelle)

**Comment by xdoo** [comment]
Das funktioniert auch ausserhalb eines Bürgers. Sobald jemand mit Kindern da ist, wandern alle Bürger, die bearbeitet wurden als Kind unter den Bürger. 

Nachstellen:
1. Einem Bürger A ein Kind hinzu fügen.
2. Zurück in die Suchtabelle. Dort einen beliebigen Bürger B zur Bearbeitung auswählen.
3. Nach speichern befindet man sich in der Detailansicht von A und B ist ein Kind von A.

**Comment by darenegade** [comment]
Das liegt sehr wahrscheinlich an den persistenen Components. Beim erstellen der Table wird ja überprüft, ob es schon einen entsprechende Tabelle gibt und nimmt diese dann her.
D.h. Bei Bürger A wird die Tabelle neu erstellt und bei Bürger B wird die alte gespeicherte Tabelle von A wieder hergenommen.

Hier muss beim Speichern noch zur Komponete ein Identifiere mit gespeichert werden.
