### ISSUE TITLE
Bibliothek anlegen für: Service-Info

### ISSUE THREAD

**Issue by martku** [xdoo/vaadin-demo#84]
Durch den generativen Ansatz (#3) ist es sinnvoll die Service-Info (eventuell mit weiteren zusammengehörigen Teilen) in eine eigene wiederverwendbare Bibliothek auszulagern.

**Comment by Arne2** [comment]
Service-Info mit restlichen API Teile, die später nicht generiert werden in API-Lib ausgelagert.
