### ISSUE TITLE
Bibliothek anlegen für: I18N

### ISSUE THREAD

**Issue by martku** [xdoo/vaadin-demo#85]
Durch den generativen Ansatz (#3) ist es sinnvoll den I18N-Teil in eine eigene wiederverwendbare Bibliothek auszulagern.

**Comment by Arne2** [comment]
I18nService und I18nServiceConfigImpl jetzt im Modul I18nService

**Comment by Arne2** [comment]
ControllerContext und Buttons jetzt auch im Modul
Anmerkung: Api ist jetzt dependency (nur BaseEntitiy wird benötigt, also keine generierten Klassen)
