### ISSUE TITLE
Validierung auf REST Server Seite

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/vaadin-demo#90]
Bei den Entitäten des Microservice könnte immer validiert werden.

``` java
@Entity
@Audited
@Indexed
@Table(name = "BUERGER")
public class Buerger extends BaseEntity {

    @Field
    @Column(length = 70, nullable = true, name = "BUER_VORNAME")
    private String vorname;

    private String setVorname(String vorname) {
        if ("peter".equals(vorname))
            throw new IllegalArgumentException("asdf");
        this.vorname = vorname;
    }
}
```

Die Response mit Spring Data Rest bei einem `POST` mit fehlerhaften Vornamen schaut dann _ca._ so aus:

``` json
{
    "message": "asdf",
    "cause": {}
}
```

Ist eine Validierung auf Server Seite gewünscht? 
_das könnte recht einfach mit generiert werden_

**Comment by martku** [comment]
Bitte zur Validierung JSR 303 nutzen. Ein kleines Beispiel, bei der auch ein Regex (kann in Barrakuda auch angegeben werden) validiert wird:
http://howtodoinjava.com/2015/02/12/spring-bean-validation-example-with-jsr-303-annotations/

**Comment by peter-mueller** [comment]
Dann schauen Fehlermeldungen so aus:

``` html
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Sep 08 10:12:38 CEST 2015</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Validation failed for classes [de.muenchen.kvr.domain.Buerger] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
    ConstraintViolationImpl{interpolatedMessage=&#39;LOL&#39;, propertyPath=nachname, rootBeanClass=class de.muenchen.kvr.domain.Buerger, messageTemplate=&#39;LOL&#39;}
]</div></body></html>
```

Ist das egal?

**Comment by xdoo** [comment]
Wird hier auch ein Statuscode zurück geliefert? Ich denke 422 würde z.B. passen. Wenn ein entsprechender Statuscode zurück geliefert wird, dann ist die Payload erst einmal egal.
