### ISSUE TITLE
Service Aufrufe über Netflix Hystrix

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#95]
Service Aufrufe aus dem micro Service sollten über Netflix Hystrix erfolgen, um im Fehlerfall eines erxternen Services besser reagieren zu können. 

Wie es mit Spring Cloud geht:
http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html

Schöner Artikel über Histrix:
https://plus.google.com/+ClausStraube/posts/3Af5RAhRo98

Hystrix Doku:
https://github.com/Netflix/Hystrix/wiki

**Comment by FabianWilms** [comment]
@peter-mueller Ich weiß wirklich nicht ob wir Hystrix auch auf GUI-Seite zum Fehler abfangen nutzen sollten. Im MicroService macht Hystrix ohne Frage Sinn, allerdings bin ich gerade auf folgendes Problem bei der Implementierung im BuergerService gestoßen:

Bei Verwendung der `@HystrixCommand`-annotation hast du für jede Methode eine fallback-methode, diese muss immer die gleiche Signatur haben wie die annotierte methode. Allerdings komme ich in dieser Methode nicht an den Auslöser ran, weshalb Hystrix ausgelöst hat. Somit kann ich wirklich immer nur eine generische Fehlermeldung liefern. Irgendwie unschön.

Lösung wäre den Service die Klasse `HystrixCommand<T>` erweitern zu lassen. Da könnte man anhand des cause speziellere fehlermeldungen anzeigen. Problem dabei: Es gibt nur eine fallback-methode, und diese gilt nur für methoden die T zurückliefern. Also auch blöd.

Meiner Meinung nach sollten wir auf GUI-Seite wirklich darüber nachdenken "eigenes" Fehlerhandling in dem Sinne einzubauen, dass wir http-exceptions die bei den Service-Anfragen auftreten können (409, 401, 404 etc..) direkt abfangen und im buergerservice darauf reagieren. Das korrekte fluchtwerte vom micro-service geliefert werden wird schließlich durch den einsatz von Hystrix im MicroService gewährleistet.

**Comment by peter-mueller** [comment]
Ich finde die momentane Lösung sehr geil, da so simpel!

**Comment by darenegade** [comment]
@FabianHoltkoetter Kommt man nicht über den HystrixRequestLog an die Exception?
https://github.com/Netflix/Hystrix/issues/828

Ansonsten sehe ich das wie der Fabian. Der Fehler sollte nicht einfach verschluckt werden. Vielleicht ist der Ansatz mit einer Anonymen Klasse für die HystrixCommands auch für uns passend. 
https://github.com/spring-cloud/spring-cloud-netflix/issues/195

**Comment by FabianWilms** [comment]
@darenegade Danke für den Link. Werde ich mir mal anschauen. Habe gestern nichts richtiges gefunden gehabt, aber das klingt vielversprechend!

**Comment by FabianWilms** [comment]
Das funktioniert leider auch nicht. Der HystrixRequestLog liefert leider trotz initialisierung keine Requests zurück. Außerdem sahen die Methoden durch das ständige Kontext initialisieren und wieder aufheben extrem schlimm aus. Zusätzlich hatte man um das ganze so zu nutzen drei weitere Abhängigkeiten in der POM des GUI-Moduls. Ich werde das ganze auf GUI-Seite nun mit try-catch umsetzen. Im Microservice werde ich dann allerdings die Fallback-Methoden nutzen.

**Comment by peter-mueller** [comment]
https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/README.md

**Comment by FabianWilms** [comment]
Worauf möchtest du mich hinweisen? :smile: 

@darenegade && @peter-mueller : Ich habe mich gerade mit @xdoo diesbezüglich unterhalten. Ihm sind aussagekräfte Benachrichtigungen wichtiger. Er sagt, die try-catch-implementierung so beibehalten, und zusätzlich die reactor streams für die Anfrage selbst verwenden, da man dort ebenfalls einen Timeout einstellen kann, um ein einfrieren der GUI zu verhindern.

**Comment by darenegade** [comment]
Kannst du das mit den Reaktor Streams erklären, was du damit meinst? 

Warum nicht die anonymen Klassen von hystrix? 

Von meinem iPhone gesendet

**Comment by FabianWilms** [comment]
Reactor streams ist doch eher eine bescheidene alternative dafür, die sind eher für mehrere anfragen hintereinander geeignet. Damit hätte es so ausgesehen:

``` java
Broadcaster<Buerger> stream = Broadcaster.create();
Promise<Buerger> promise = stream.timeout(TIMEOUT).map(client::create).next();

stream.onNext(buerger);
promise.await();
returnBuerger = promise.get();
```

Ich verwende jetzt die Java-eigene Klasse `ExecutorService` um Methoden einen timeout vorzuschreiben, unter anderem auch, weil weitere imports aus dem reactor-package den eventbus sehr unglücklich gemacht haben. sieht jetzt so aus:

``` java
ExecutorService executorService = Executors.newCachedThreadPool();
Callable<Buerger> createTask = () -> client.create(buerger);
Future<Buerger> result = executorService.submit(createTask);
returnBuerger = result.get(TIMEOUT, TimeUnit.SECONDS);
```

:pencil2: Edit:
@xdoo Für dich so auch i.O.?

**Comment by Arne2** [comment]
Nach Fertigstellung Ticket Nr53(martkhm/barrakuda#53) in Barrakuda Bescheid geben.

**Comment by FabianWilms** [comment]
Sollte dennoch Interesse an der Funktionalität bestehen, dass nach mehreren Fehlgeschlagenen Service-Aufrufen immer der Fallback verwendet werden soll, ließe sich dies auch über Spring lösen.

http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html

Momentan sind Claus und ich allerdings der Meinung, dass wir diese funktionalität eher zurückstellen können. Schließlich sind wir mit Vaadin bereits auf der Serverseite, und sollte Vaadin keine Probleme haben, wird es im MicroService auch keine geben.
